"use client";

import React, { useActionState, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import {
  PiPackage,
  PiTruck,
  PiCheckCircle,
  PiClock,
  PiXCircle,
  PiMagnifyingGlass,
  PiArrowSquareOut,
} from "react-icons/pi";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../../../components/Select";
import { useAdminOrdersContext } from "./context";
import { updateOrderItemFulfillment } from "./action";

const initialUpdateState = {
  message: "",
  errors: {
    orderItemId: [],
    fulfillmentStatus: [],
  },
  values: {},
  data: {},
};

const fulfillmentOptions = [
  { value: "pending", label: "Pending" },
  { value: "paid", label: "Paid" },
  { value: "shipped", label: "Shipped" },
  { value: "delivered", label: "Delivered" },
  { value: "cancelled", label: "Cancelled" },
];

function formatCurrency(value) {
  const num = Number(value);
  if (!Number.isFinite(num)) return "GHS 0.00";
  return `GHS ${num.toLocaleString("en-GH", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function formatDate(value) {
  if (!value) return "—";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "—";
  return date.toLocaleString();
}

function statusBadgeClass(status) {
  const normalized = String(status || "").toLowerCase();
  if (normalized === "delivered") return "bg-green-100 text-green-700";
  if (normalized === "shipped") return "bg-blue-100 text-blue-700";
  if (normalized === "paid") return "bg-indigo-100 text-indigo-700";
  if (normalized === "cancelled") return "bg-red-100 text-red-700";
  if (normalized === "expired") return "bg-slate-100 text-slate-700";
  return "bg-amber-100 text-amber-700";
}

export default function AdminOrdersContent() {
  const {
    items,
    stats,
    loading,
    error,
    canUpdateFulfillment,
    refreshData,
  } = useAdminOrdersContext() || {};

  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [pendingItemId, setPendingItemId] = useState("");

  const [updateState, updateAction, updatePending] = useActionState(
    updateOrderItemFulfillment,
    initialUpdateState
  );

  useEffect(() => {
    if (!updateState?.message) return;
    if (updateState?.data?.orderItemId) {
      refreshData?.();
      setPendingItemId("");
    }
  }, [updateState, refreshData]);

  const filteredItems = useMemo(() => {
    const normalizedQuery = String(searchQuery || "").trim().toLowerCase();

    return (items || []).filter((item) => {
      const matchesStatus =
        statusFilter === "all" ||
        String(item.fulfillmentStatus || "").toLowerCase() === statusFilter;

      if (!normalizedQuery) return matchesStatus;

      const haystack = [
        item.orderCode,
        item.productName,
        item.productCode,
        item.vendorName,
        item.buyerName,
        item.buyerEmail,
      ]
        .map((value) => String(value || "").toLowerCase())
        .join(" ");

      return matchesStatus && haystack.includes(normalizedQuery);
    });
  }, [items, searchQuery, statusFilter]);

  if (loading) {
    return (
      <section className="flex flex-col gap-4 w-full mb-8">
        <div className="h-7 w-48 rounded-md bg-[#E5E7EB] animate-pulse" />
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-3">
          {[...Array(6)].map((_, index) => (
            <div key={index} className="h-20 rounded-xl bg-[#E5E7EB] animate-pulse" />
          ))}
        </div>
        <div className="h-72 rounded-xl bg-[#E5E7EB] animate-pulse" />
      </section>
    );
  }

  return (
    <section aria-label="Admin order operations" className="flex flex-col gap-4 w-full mb-8">
      <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm">
        <Link href="/dashboard/admin" className="text-[#6B7280] hover:text-[#111827]">
          Admin
        </Link>
        <span className="text-[#6B7280]">/</span>
        <span className="text-[#111827] font-medium">Orders</span>
      </nav>

      <div>
        <h1 className="text-[#111827] text-lg font-semibold">Order Operations</h1>
        <p className="text-[#6B7280] text-sm">
          Giftologi operations controls item-level fulfillment and tracking.
        </p>
        <p className="text-[#6B7280] text-xs mt-1">
          Tracking IDs are generated by the system on shipment and are not editable.
        </p>
      </div>

      {error ? (
        <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          {error}
        </div>
      ) : null}

      {updateState?.message ? (
        <div
          className={`rounded-lg border px-3 py-2 text-sm ${
            updateState?.data?.orderItemId
              ? "border-green-200 bg-green-50 text-green-700"
              : "border-amber-200 bg-amber-50 text-amber-700"
          }`}
        >
          {updateState.message}
        </div>
      ) : null}

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-6 gap-3">
        <StatCard icon={PiClock} label="Pending" value={stats?.pending || 0} />
        <StatCard icon={PiPackage} label="Paid" value={stats?.paid || 0} />
        <StatCard icon={PiTruck} label="Shipped" value={stats?.shipped || 0} />
        <StatCard icon={PiCheckCircle} label="Delivered" value={stats?.delivered || 0} />
        <StatCard icon={PiXCircle} label="Cancelled" value={stats?.cancelled || 0} />
        <StatCard icon={PiXCircle} label="Expired" value={stats?.expired || 0} />
      </div>

      <div className="bg-white rounded-xl border border-[#E5E7EB] overflow-hidden">
        <div className="p-4 border-b border-[#E5E7EB] flex flex-col md:flex-row gap-3 md:items-center md:justify-between">
          <div className="relative w-full md:max-w-md">
            <PiMagnifyingGlass className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#9CA3AF]" />
            <input
              type="text"
              value={searchQuery}
              onChange={(event) => setSearchQuery(event.target.value)}
              placeholder="Search by order, customer, product, or vendor"
              className="w-full pl-9 pr-3 py-2 border border-[#D1D5DB] rounded-lg text-sm"
            />
          </div>

          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-full md:w-[220px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All statuses ({items?.length || 0})</SelectItem>
              <SelectItem value="pending">Pending ({stats?.pending || 0})</SelectItem>
              <SelectItem value="paid">Paid ({stats?.paid || 0})</SelectItem>
              <SelectItem value="shipped">Shipped ({stats?.shipped || 0})</SelectItem>
              <SelectItem value="delivered">Delivered ({stats?.delivered || 0})</SelectItem>
              <SelectItem value="cancelled">Cancelled ({stats?.cancelled || 0})</SelectItem>
              <SelectItem value="expired">Expired ({stats?.expired || 0})</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1180px]">
            <thead className="bg-[#F9FAFB]">
              <tr>
                <th className="px-3 py-3 text-left text-xs font-medium text-[#6B7280] uppercase">Order</th>
                <th className="px-3 py-3 text-left text-xs font-medium text-[#6B7280] uppercase">Customer</th>
                <th className="px-3 py-3 text-left text-xs font-medium text-[#6B7280] uppercase">Vendor / Product</th>
                <th className="px-3 py-3 text-right text-xs font-medium text-[#6B7280] uppercase">Amount</th>
                <th className="px-3 py-3 text-left text-xs font-medium text-[#6B7280] uppercase">Fulfillment</th>
                <th className="px-3 py-3 text-left text-xs font-medium text-[#6B7280] uppercase">Tracking ID</th>
                <th className="px-3 py-3 text-left text-xs font-medium text-[#6B7280] uppercase">Updated</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#E5E7EB]">
              {!filteredItems.length ? (
                <tr>
                  <td colSpan={7} className="px-3 py-10 text-center text-sm text-[#6B7280]">
                    No order items match your filters.
                  </td>
                </tr>
              ) : (
                filteredItems.map((item) => {
                  const rowPending =
                    updatePending &&
                    pendingItemId &&
                    String(pendingItemId) === String(item.id);
                  const lockedByOrderStatus =
                    item.orderStatus === "cancelled" || item.orderStatus === "expired";
                  const canEditFulfillment = canUpdateFulfillment && !lockedByOrderStatus;

                  return (
                    <tr key={item.id} className="align-top">
                      <td className="px-3 py-3">
                        <Link
                          href={`/dashboard/admin/transactions?focusId=${item.orderId}`}
                          className="inline-flex items-center gap-1 text-sm font-medium text-[#111827] hover:text-primary"
                        >
                          {item.orderCode}
                          <PiArrowSquareOut className="w-3.5 h-3.5" />
                        </Link>
                        <div className="text-xs text-[#6B7280]">{formatDate(item.createdAt)}</div>
                        <div className="mt-1 inline-flex items-center px-2 py-0.5 rounded-full text-[11px] bg-[#F3F4F6] text-[#4B5563]">
                          Order: {item.orderStatus}
                        </div>
                      </td>
                      <td className="px-3 py-3 text-sm text-[#111827]">
                        <div>{item.buyerName}</div>
                        {item.buyerEmail ? (
                          <div className="text-xs text-[#6B7280]">{item.buyerEmail}</div>
                        ) : null}
                        {item.shippingCity || item.shippingRegion ? (
                          <div className="text-xs text-[#6B7280] mt-1">
                            {item.shippingCity || ""}
                            {item.shippingCity && item.shippingRegion ? ", " : ""}
                            {item.shippingRegion || ""}
                          </div>
                        ) : null}
                        {item.shippingAddress ? (
                          <div className="text-xs text-[#6B7280] mt-1">
                            {item.shippingAddress}
                          </div>
                        ) : null}
                        {item.shippingDigitalAddress ? (
                          <div className="text-xs text-[#4B5563] mt-1">
                            Digital address: {item.shippingDigitalAddress}
                          </div>
                        ) : null}
                      </td>
                      <td className="px-3 py-3 text-sm">
                        <div className="font-medium text-[#111827]">{item.vendorName}</div>
                        <div className="text-[#111827]">{item.productName}</div>
                        <div className="text-xs text-[#6B7280]">SKU: {item.productCode}</div>
                        <div className="text-xs text-[#6B7280]">Qty: {item.quantity}</div>
                      </td>
                      <td className="px-3 py-3 text-sm text-right">
                        <div className="font-medium text-[#111827]">{formatCurrency(item.totalAmount)}</div>
                        <div className="text-xs text-[#6B7280]">Unit {formatCurrency(item.unitPrice)}</div>
                      </td>
                      <td className="px-3 py-3 space-y-2">
                        <span
                          className={`inline-flex items-center px-2.5 py-1 text-xs font-medium rounded-full ${statusBadgeClass(
                            item.fulfillmentStatus
                          )}`}
                        >
                          {item.fulfillmentStatus}
                        </span>
                        {item.fulfillmentStatusRaw !== item.fulfillmentStatus ? (
                          <p className="text-[11px] text-[#6B7280]">
                            Synced from order status ({item.orderStatus})
                          </p>
                        ) : null}
                        {canEditFulfillment ? (
                          <form action={updateAction} className="space-y-2">
                            <input type="hidden" name="orderItemId" value={item.id} readOnly />
                            <select
                              name="fulfillmentStatus"
                              defaultValue={item.fulfillmentStatusRaw || item.fulfillmentStatus}
                              className="w-full min-w-[140px] rounded-md border border-[#D1D5DB] px-2 py-1.5 text-xs"
                            >
                              {fulfillmentOptions.map((option) => (
                                <option key={option.value} value={option.value}>
                                  {option.label}
                                </option>
                              ))}
                            </select>
                            <button
                              type="submit"
                              onClick={() => setPendingItemId(item.id)}
                              disabled={rowPending}
                              className="w-full rounded-md bg-[#111827] text-white text-xs font-medium px-2 py-1.5 disabled:opacity-50"
                            >
                              {rowPending ? "Saving..." : "Save"}
                            </button>
                          </form>
                        ) : (
                          <span className="text-xs text-[#6B7280]">
                            {lockedByOrderStatus
                              ? `Read-only (${item.orderStatus} order)`
                              : "Read-only"}
                          </span>
                        )}
                      </td>
                      <td className="px-3 py-3 text-xs text-[#6B7280]">
                        {item.trackingNumber ? (
                          <span className="font-medium text-[#111827]">{item.trackingNumber}</span>
                        ) : (
                          <span>Auto-generated once shipped</span>
                        )}
                      </td>
                      <td className="px-3 py-3 text-xs text-[#6B7280]">
                        {formatDate(item.updatedAt)}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

function StatCard({ icon: Icon, label, value }) {
  return (
    <div className="bg-white border border-[#E5E7EB] rounded-xl p-3">
      <div className="flex items-center justify-between">
        <span className="text-xs text-[#6B7280]">{label}</span>
        <Icon className="w-4 h-4 text-[#6B7280]" />
      </div>
      <div className="mt-2 text-xl font-semibold text-[#111827]">{value}</div>
    </div>
  );
}
